language: node_js
 
node_js:
  - '4'
 
branches:
  only:
  - master
 
cache:
  directories:
  - node_modules
 
before_install:
- openssl aes-256-cbc -K $encrypted_6ea511e3a447_key -iv $encrypted_6ea511e3a447_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id2_rsa -d
- chmod 600 ~/.ssh/id2_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id2_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "devlee"
- git config --global user.email "devlee@outlook.com"
 
install:
- npm install hexo-cli -g
- npm install
 
script:
- hexo clean
- hexo g
 
after_success:
- hexo deploy
